import logging
import os
import uuid
import config
from flask import request

from flask_smorest import abort
from werkzeug.utils import secure_filename

from app.db import db
from app.models import Model, File, ModelIssue
from app.types import DetectionStage
from config import FeatureToggle, DefaultConfig
from datetime import datetime
from app.services.geometry_service import (
    run_inspect_for_file_upload,
    run_repair_pipeline
)
# Create logger for this module
logger = logging.getLogger(__name__)

def create_new_model(model_data):
    logger.warning(f"Creating new model with data: {model_data}")
    new_model = Model(
        name=model_data["name"],
        projectId=model_data["projectId"],
        sourceFileId=model_data["sourceFileId"],
        outputFileId=model_data["sourceFileId"],
        imagePath=model_data["imagePath"] if "imagePath" in model_data else None,
    )

    db.session.add(new_model)
    try:
        db.session.flush()

        if FeatureToggle.is_enabled("enable_geo_conversion"):

            directory = DefaultConfig.UPLOAD_FOLDER
            file = File.query.filter_by(id=model_data["sourceFileId"]).first()
            if file:
                file_name, _ = os.path.splitext(os.path.basename(file.fileName))
                inital_issue_path = os.path.join(directory, f"{file_name}_inspect_issue.json")
                issue_path = os.path.join(directory, f"{file_name}_remaining_issue.json")
                obj_path = os.path.join(directory, f"{file_name}.obj")
                try: 
                    file_geo = File(fileName=f"{file_name}.geo")
                    new_model.hasGeo = True
                    db.session.add(file_geo)

                    # Run the inspect pipeline to generate an issue report for the uploaded file
                    _, issue_count = run_inspect_for_file_upload(file_name, directory)
                    # logger.warning(
                    #     f"Inspect report for file upload {model_data['sourceFileId']} generated at: {issue_path} with {issue_count} issues found"
                    # )
                    # Write the model issue to the database, and create a File record for the .geo file that will be generated by the repair pipeline
                    # Expose the issue report as a URL so the frontend can fetch it
                    initial_issue_filename = os.path.basename(inital_issue_path)
                    initial_issue_url = f"{request.host_url}{DefaultConfig.UPLOAD_FOLDER_NAME}/{initial_issue_filename}"

                    initial_model_path = os.path.join(directory, f"{file_name}.3dm")
                    initial_model_url = f"{request.host_url}{DefaultConfig.UPLOAD_FOLDER_NAME}/{os.path.basename(initial_model_path)}"
                    logger.warning(
                        f"Inspect report for file upload {model_data['sourceFileId']} generated at: {issue_path} with {issue_count} issues found. Accessible at: {initial_issue_url}"
                    )
                    model_issue = ModelIssue(
                        modelId=new_model.id,
                        fileUrl=initial_issue_url,
                        issueCount=issue_count,
                        detectionStage=DetectionStage.AfterUpload,
                        modelFileUrl=initial_model_url
                    )

                    db.session.add(model_issue)

                    run_repair_pipeline(
                        obj_path,
                        directory,
                        volume_name="RoomVolume",
                    )

                    issue_filename = os.path.basename(issue_path)
                    issue_url = f"{request.host_url}{DefaultConfig.UPLOAD_FOLDER_NAME}/{issue_filename}"
                    repaired_model_path = os.path.join(directory, f"{file_name}_repaired.3dm")
                    repaired_model_url = f"{request.host_url}{DefaultConfig.UPLOAD_FOLDER_NAME}/{os.path.basename(repaired_model_path)}"
                    
                    repaired_model_issue = ModelIssue(
                        modelId=new_model.id,
                        fileUrl=issue_url,
                        # issue count still hardcoded here
                        issueCount=10,
                        detectionStage=DetectionStage.AfterRepair,
                        modelFileUrl=repaired_model_url  
                    )

                    db.session.add(repaired_model_issue)
                except Exception as ex:
                    # don't abort creation for pipeline failures; log and continue
                    db.session.rollback()
                    logger.warning(
                        f"Failed to run geometry repair pipeline for source file {file.fileName}: {ex}"
                    )

        # commit the model (and File, model_issue) together
        db.session.commit()
    except Exception as ex:
        db.session.rollback()
        logger.error(f"Can not create a new model: {ex}")
        abort(400, f"Can not create a new model: {ex}")

    return new_model

def get_model(model_id):
    model = Model.query.filter_by(id=model_id).first()
    if not model:
        logger.error("Model with id " + str(model_id) + "does not exists!")
        abort(404, "Model does not exist")
    return model


def update_model(model_id, model_data):
    model = Model.query.filter_by(id=model_id).first()
    if not model:
        logger.error("Model doesn't exist, cannot update!")
        abort(400, "Model doesn't exist, cannot update!")

    try:
        model.name = model_data["name"]
        model.updatedAt = datetime.now()
        db.session.commit()
    except Exception as ex:
        db.session.rollback()
        logger.error(f"Can not update! Error: {ex}")
        abort(400, message=f"Can not update! Error: {ex}")

    return model


def delete_model(model_id):
    model = Model.query.filter_by(id=model_id).first()
    if not model:
        logger.error("Model doesn't exist, cannot delete!")
        abort(404, "Model doesn't exist, cannot delete!")

    # Attempt to remove associated image asset if present
    if model.imagePath:
        image_path = model.imagePath
        # Build absolute path when a relative uploads path is stored
        if not os.path.isabs(image_path):
            image_path = os.path.join(config.basedir, image_path)
        try:
            if os.path.exists(image_path):
                os.remove(image_path)
        except Exception as ex:
            # Log and continue deleting the model even if file removal fails
            logger.warning(f"Failed to remove image asset '{image_path}': {ex}")

    try:
        db.session.delete(model)
        db.session.commit()
    except Exception as ex:
        db.session.rollback()
        logger.error(f"Error deleting the model!: {ex}")
        abort(500, f"Error deleting the model!: {ex}")


def upload_image(files):
    if 'file' not in files:
        logger.error("No file provided in the request")
        abort(400, message="No file provided")
    
    upload_file = files['file']
    
    if upload_file.filename == "":
        logger.error("No file selected")
        abort(400, message="No file selected")
    
    # Check if file has allowed extension
    allowed_image_extensions = {'png', 'jpg', 'jpeg'}
    if not ('.' in upload_file.filename and 
            upload_file.filename.rsplit('.', 1)[1].lower() in allowed_image_extensions):
        logger.error(f"File type not allowed: {upload_file.filename}")
        abort(400, message="Invalid file type. Allowed types: png, jpg, jpeg")
    
    try:
        # Secure the filename and create unique name
        filename = secure_filename(upload_file.filename)
        file_ext = filename.rsplit(".", 1)[1].lower()
        unique_filename = f"{filename.rsplit('.', 1)[0]}_{uuid.uuid4().hex}.{file_ext}"
        
        # Save the file
        file_path = os.path.join(DefaultConfig.USER_MODEL_IMAGE_FOLDER_NAME, unique_filename)
        upload_file.save(file_path)
        
        # Return the relative path
        return {"imagePath": f"{DefaultConfig.USER_MODEL_IMAGE_FOLDER_NAME}/{unique_filename}"}
    
    except Exception as ex:
        logger.error(f"Error uploading image file: {ex}")
        abort(500, message=f"Error uploading image file: {ex}")
