"""Add errorMessage to simulations and simulationRuns

Revision ID: 9b846e1fdacb
Revises: aa014146bd5b
Create Date: 2026-08-17 16:11:39.614696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b846e1fdacb'
down_revision = 'aa014146bd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationRuns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('errorMessage', sa.String(), nullable=True))

    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('errorMessage', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_column('errorMessage')

    with op.batch_alter_table('simulationRuns', schema=None) as batch_op:
        batch_op.drop_column('errorMessage')

    # ### end Alembic commands ###
