"""Initial schema baseline (pre-errorMessage)

Revision ID: aa014146bd5b
Revises: 
Create Date: 2026-08-17 16:08:43.494227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa014146bd5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fileName', sa.String(), nullable=True),
    sa.Column('slot', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulationRuns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('receivers', sa.JSON(), nullable=True),
    sa.Column('simulationMethod', sa.String(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.Column('settingsPreset', sa.Enum('Default', 'Advanced', name='setting'), nullable=True),
    sa.Column('layerIdByMaterialId', sa.JSON(), nullable=True),
    sa.Column('solverSettings', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('Uncreated', 'Created', 'Queued', 'InProgress', 'ProcessingResults', 'Completed', 'Cancelled', 'Error', name='status'), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.Column('completedAt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_settings',
    sa.Column('simulationType', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('repositoryURL', sa.String(), nullable=True),
    sa.Column('documentationURL', sa.String(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('simulationType')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taskType', sa.Enum('GeometryCheck', 'Mesh', 'SimulationMethod', 'Generic', name='tasktype'), nullable=True),
    sa.Column('status', sa.Enum('Uncreated', 'Created', 'Queued', 'InProgress', 'ProcessingResults', 'Completed', 'Cancelled', 'Error', name='status'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.Column('completedAt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('isUserFile', sa.Boolean(), nullable=True),
    sa.Column('fileExtension', sa.String(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('geometries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inputModelUploadId', sa.Integer(), nullable=False),
    sa.Column('outputModelId', sa.Integer(), nullable=True),
    sa.Column('taskId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['taskId'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('absorptionCoefficients', sa.JSON(), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['material_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meshes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taskId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.Column('completedAt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['taskId'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sourceFileId', sa.Integer(), nullable=False),
    sa.Column('outputFileId', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('meshId', sa.Integer(), nullable=True),
    sa.Column('hasGeo', sa.Boolean(), nullable=False),
    sa.Column('imagePath', sa.String(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['meshId'], ['meshes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('hasBeenEdited', sa.Boolean(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('receivers', sa.JSON(), nullable=True),
    sa.Column('resourceType', sa.Enum('LOCAL', 'CLOUD', name='resourcetype'), nullable=True),
    sa.Column('simulationMethod', sa.String(), nullable=True),
    sa.Column('layerIdByMaterialId', sa.JSON(), nullable=True),
    sa.Column('settingsPreset', sa.Enum('Default', 'Advanced', name='setting'), nullable=True),
    sa.Column('solverSettings', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('Uncreated', 'Created', 'Queued', 'InProgress', 'ProcessingResults', 'Completed', 'Cancelled', 'Error', name='status'), nullable=True),
    sa.Column('modelId', sa.Integer(), nullable=False),
    sa.Column('simulationRunId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.Column('completedAt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['modelId'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulationRunId'], ['simulationRuns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auralizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulationId', sa.Integer(), nullable=True),
    sa.Column('audioFileId', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Uncreated', 'Created', 'Queued', 'InProgress', 'ProcessingResults', 'Completed', 'Cancelled', 'Error', name='status'), nullable=True),
    sa.Column('wavFileName', sa.String(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['audioFileId'], ['audio_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulationId'], ['simulations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='xlsx file name'),
    sa.Column('simulationId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['simulationId'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exports')
    op.drop_table('auralizations')
    op.drop_table('simulations')
    op.drop_table('models')
    op.drop_table('meshes')
    op.drop_table('materials')
    op.drop_table('geometries')
    op.drop_table('audio_files')
    op.drop_table('user_preferences')
    op.drop_table('tasks')
    op.drop_table('simulation_settings')
    op.drop_table('simulationRuns')
    op.drop_table('projects')
    op.drop_table('material_categories')
    op.drop_table('files')
    # PostgreSQL retains named enum types after their tables are dropped;
    # explicitly clean them up so a subsequent upgrade starts from a clean state.
    for enum_name in ('status', 'setting', 'resourcetype', 'tasktype'):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
